### ISSUE TITLE
wsl-archlinux is outdated, simple upgrade not possible

### ISSUE THREAD

**Issue by damian101** [bcurran3/ChocolateyPackages#198]
A simple upgrade is not possible as the pacman version in wsl-archlinux doesn't support zstd.

**Comment by bcurran3** [comment]
Your saying you can't upgrade packages because, pacman, the program to upgrade packages, doesn't support zstd. This seems like something that just isn't likely the devs would make it impossible to upgrade packages and something that should be addressed to the devs.

I'm sure I'm not understanding the problem, so could you explain with more detail please?

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
